export const roles = [
    { value: "MainTank", label: "MainTank", icon: "/rolesIcons/maintank.webp" },
    { value: "OffTank", label: "OffTank", icon: "/rolesIcons/offtank.webp" },
    { value: "Arcano Silence", label: "Arcano Silence", icon: "/rolesIcons/arcanosilence.webp" },
    { value: "Arcano Elevado", label: "Arcano Elevado", icon: "/rolesIcons/arcanoelevado.webp" },
    { value: "Main Healer", label: "Main Healer", icon: "/rolesIcons/mainhealer.webp" },
    { value: "Bruxo", label: "Bruxo", icon: "/rolesIcons/bruxo.webp" },
    { value: "Quebra Reinos", label: "Quebra Reinos", icon: "/rolesIcons/quebrareinos.webp" },
    { value: "Incubus", label: "Incubus", icon: "/rolesIcons/incubus.webp" },
    { value: "Oculto", label: "Oculto", icon: "/rolesIcons/oculto.png" },
    { value: "Raiz Férrea", label: "Raiz Férrea", icon: "/rolesIcons/raiz.webp" },
    { value: "Raiz Férrea - DPS", label: "Raiz Férrea - DPS", icon: "/rolesIcons/raizDps.webp" },
    { value: "X-Bow", label: "X-Bow", icon: "/rolesIcons/xbow.webp" },
    { value: "Águia", label: "Águia", icon: "/rolesIcons/aguia.webp" },
    { value: "Frost", label: "Frost", icon: "/rolesIcons/frost.webp" },
    { value: "Fire", label: "Fire", icon: "/rolesIcons/fire.webp" },
    { value: "Role Troll", label: "Role Troll", icon: "/rolesIcons/roletroll.png" },
    //{ value: "Scout", label: "Scout", icon: "/rolesIcons/scout.webp" },
  ]